%define _unpackaged_files_terminate_build 1

Name:           semtools
Version:        3.0.1
Release:        alt1

Summary:        Semantic search and document parsing tools for the command line
License:        MIT
Group:          File tools
URL:            https://github.com/run-llama/semtools
VCS:            https://github.com/run-llama/semtools

Source:         %name-%version.tar
# Dependency source code archive (vendor dependencies)
# Generated by the <cargo-vendor-alt> command.
Source1:        vendor.tar

BuildRequires(pre): rpm-build-rust
BuildRequires: gcc-c++
BuildRequires: protobuf-compiler
BuildRequires: libprotobuf-devel

%description
A high-performance CLI tool for document processing and semantic search,
built with Rust for speed and reliability.

%prep
%setup -a 1 -q
%rust_prep

%build
export PROTOC=%_bindir/protoc
export PROTOC_INCLUDE=%_includedir
cargo build --release -j2 --offline

%install
%rust_install

# These tests require network access.
%check
%rust_test -- --skip test_create_document \
                   --skip test_search_documents \
                   --skip test_search_result \
                   --skip test_empty_documents \
                   --skip test_multiple_documents \
                   --skip test_context_at_file_boundaries \
                   --skip test_case_insensitive_search \
                   --skip test_create_document_from_empty_content \
                   --skip test_create_document_with_case_insensitive \
                   --skip test_search_documents_top_k_limit \
                   --skip test_search_documents_with_max_distance \
                   --skip test_search_result_context_calculation

%files
%_bindir/%name
%doc README.md

%changelog
* Fri May 15 2026 Mikhail Kotyukhov <legend@altlinux.org> 3.0.1-alt1
- Initial build for Sisyphus.